rootProject.name = 'HIRS'

include 'HIRS_Utils',
        'HIRS_AttestationCA',
        'HIRS_AttestationCAPortal',
        ':tools:tcg_eventlog_tool',
        ':tools:tcg_rim_tool'

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            from(files("gradle/versions.toml"))
        }
    }
    repositories {
        maven { url = uri("https://googleapis.com") } // default to google mirror
        maven { url = uri("https://packages.atlassian.com/mvn/maven-atlassian-external/") } // fallback to cloudflares mirror
        mavenCentral() // Fallback to maven
    }
}