using Google.Protobuf;
using Hirs.Pb; // Imports ProvisionerTpm2.proto (compiled and generated by protobuf)
using Serilog;
using System.Net;
using System.Net.Security;
using System.Security.Cryptography;

namespace hirs {
    public class Client : IHirsAcaClient {
        public static readonly string POST_IDENTITY_CLAIM_PATH = "HIRS_AttestationCA/identity-claim-tpm2/process";
        public static readonly string POST_REQUEST_CERT_TPM2_PATH = "HIRS_AttestationCA/request-certificate-tpm2";

        private readonly Uri uri;
        private static readonly HttpClientHandler handler = CreateHandler();
        private readonly HttpClient client;

        /**
         * This method will create an HttpClient that will accept any server certificate.
         */
        public Client(string address) {
            uri = new(address);
            client = new HttpClient(handler);
            LogConnectionTarget(uri);
        }

        public Client(string address, HttpClient httpClient) {
            uri = new(address);
            client = httpClient;
            LogConnectionTarget(uri);
        }

        public async Task<IdentityClaimResponse> PostIdentityClaim(IdentityClaim identityClaim) {
            MemoryStream stream = new(identityClaim.ToByteArray());
            // serialize to stream

            stream.Seek(0, SeekOrigin.Begin);
            Uri full_address = new(uri.AbsoluteUri + POST_IDENTITY_CLAIM_PATH);
            // send data via HTTP
            StreamContent streamContent = new(stream);
            streamContent.Headers.TryAddWithoutValidation("Content-Type", "application/octet-stream");
            streamContent.Headers.TryAddWithoutValidation("Accept", "application/octet-stream, application/json");

            IdentityClaimResponse icr = null;
            try {
                Log.Debug("Attempting to send IdentityClaim to " + full_address);
                HttpResponseMessage response = await client.PostAsync(full_address, streamContent).ConfigureAwait(continueOnCapturedContext: false);
                LogResponseConnectionInfo(response, full_address);
                if (response.StatusCode == HttpStatusCode.OK) {
                    byte[] contentBytes = await response.Content.ReadAsByteArrayAsync();
                    icr = IdentityClaimResponse.Parser.ParseFrom(contentBytes);
                    Log.Debug("IdentityClaim delivery succeeded.");
                } else {
                    throw new AcaClientException($"The ACA returned HTTP {(int)response.StatusCode} ({response.ReasonPhrase}) while processing the identity claim.");
                }
            } catch (HttpRequestException e) {
                throw new AcaConnectionException("Could not connect to the ACA while sending the identity claim.", e);
            } catch (TaskCanceledException e) {
                throw new AcaConnectionException("The connection to the ACA timed out while sending the identity claim.", e);
            } catch (AcaClientException) {
                throw;
            } catch (Exception e) {
                throw new AcaClientException("The ACA returned an invalid identity-claim response.", e);
            }
            return icr;
        }

        public IdentityClaim CreateIdentityClaim(DeviceInfo dv, byte[] akPublicArea, byte[] ekPublicArea,
                                       byte[] endorsementCredential, List<byte[]> platformCredentials,
                                       string paccoroutput, byte[] ldevidPublicArea = null) {
            IdentityClaim identityClaim = new();
            identityClaim.ClientVersion = Program.VERSION;
            identityClaim.Dv = dv;
            identityClaim.AkPublicArea = ByteString.CopyFrom(akPublicArea);
            identityClaim.EkPublicArea = ByteString.CopyFrom(ekPublicArea);
            identityClaim.EndorsementCredential = ByteString.CopyFrom(endorsementCredential);
            if (platformCredentials != null) {
                foreach (byte[] platformCertificate in platformCredentials) {
                    identityClaim.PlatformCredential.Add(ByteString.CopyFrom(platformCertificate));
                }
            }
            identityClaim.PaccorOutput = paccoroutput;
            if (ldevidPublicArea != null) identityClaim.LdevidPublicArea = ByteString.CopyFrom(ldevidPublicArea);
            
            return identityClaim;
        }

        public async Task<CertificateResponse> PostCertificateRequest(CertificateRequest certReq) {
            MemoryStream stream = new(certReq.ToByteArray());
            // serialize to stream

            stream.Seek(0, SeekOrigin.Begin);
            Uri full_address = new(uri.AbsoluteUri + POST_REQUEST_CERT_TPM2_PATH);
            // send data via HTTP
            StreamContent streamContent = new(stream);
            streamContent.Headers.TryAddWithoutValidation("Content-Type", "application/octet-stream");
            streamContent.Headers.TryAddWithoutValidation("Accept", "application/octet-stream, application/json");

            CertificateResponse cr = null;
            try {
                Log.Debug("Attempting to send the Certificate Request to " + full_address);
                HttpResponseMessage response = await client.PostAsync(full_address, streamContent).ConfigureAwait(continueOnCapturedContext: false);
                LogResponseConnectionInfo(response, full_address);
                if (response.StatusCode == HttpStatusCode.OK) {
                    byte[] contentBytes = await response.Content.ReadAsByteArrayAsync();
                    cr = CertificateResponse.Parser.ParseFrom(contentBytes);
                    Log.Debug("Certificate Response recevied.");
                } else {
                    throw new AcaClientException($"The ACA returned HTTP {(int)response.StatusCode} ({response.ReasonPhrase}) while processing the certificate request.");
                }
            } catch (HttpRequestException e) {
                throw new AcaConnectionException("Could not connect to the ACA while sending the certificate request.", e);
            } catch (TaskCanceledException e) {
                throw new AcaConnectionException("The connection to the ACA timed out while sending the certificate request.", e);
            } catch (AcaClientException) {
                throw;
            } catch (Exception e) {
                throw new AcaClientException("The ACA returned an invalid certificate response.", e);
            }
            return cr;
        }

        public CertificateRequest CreateAkCertificateRequest(byte[] secret, CommandTpmQuoteResponse ctqr) {
            CertificateRequest akCertReq = new();
            akCertReq.Nonce = ByteString.CopyFrom(secret);
            CommandTpmQuoteResponse.formatQuoteInfoSigForAca(ctqr.quoted, ctqr.signature, out string quoteInfoSigStr);
            akCertReq.Quote = ByteString.CopyFromUtf8(quoteInfoSigStr);
            //formatPcrValuesForAca(pcrValues, out string pcrValuesStr);
            //akCertReq.Pcrslist = ByteString.CopyFromUtf8(pcrValuesStr);

            return akCertReq;
        }

        private static HttpClientHandler CreateHandler() {
            HttpClientHandler acaHandler = new() {
                // TODO: Overhaul ACA security
                ServerCertificateCustomValidationCallback = LogServerCertificate
            };
            Log.Debug("ACA TLS configuration: OS-default TLS protocol selection; custom certificate validation is enabled.");
            return acaHandler;
        }

        private static bool LogServerCertificate(HttpRequestMessage request,
                                                 System.Security.Cryptography.X509Certificates.X509Certificate2 certificate,
                                                 System.Security.Cryptography.X509Certificates.X509Chain chain,
                                                 SslPolicyErrors errors) {
            if (certificate == null) {
                Log.Debug("TLS connection to {Host} did not provide a server certificate.", request.RequestUri?.Host);
            } else {
                Log.Debug("TLS server certificate: subject={Subject}, issuer={Issuer}, thumbprint={Thumbprint}, validFrom={ValidFrom:u}, validTo={ValidTo:u}, policyErrors={PolicyErrors}",
                    certificate.Subject, certificate.Issuer, certificate.Thumbprint,
                    certificate.NotBefore, certificate.NotAfter, errors);
            }

            Log.Debug("TLS certificate validation result for {Host}: {PolicyErrors}. Certificate accepted by current ACA client policy.", request.RequestUri?.Host, errors);
            return true;
        }

        private static void LogConnectionTarget(Uri target) {
            Log.Debug("ACA connection target: scheme={Scheme}, host={Host}, port={Port}, TLS={Tls}",
                target.Scheme, target.Host, target.Port, target.Scheme.Equals(Uri.UriSchemeHttps, StringComparison.OrdinalIgnoreCase));
        }

        private static void LogResponseConnectionInfo(HttpResponseMessage response, Uri target) {
            Log.Debug("ACA connection response: target={Target}, status={StatusCode}, reason={ReasonPhrase}, requestHttpVersion={RequestVersion}, responseHttpVersion={ResponseVersion}, server={Server}",
                target, (int)response.StatusCode, response.ReasonPhrase,
                response.RequestMessage?.Version, response.Version,
                response.Headers.Server);
        }
    }
}
