//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.16 at 06:40:19 PM UTC 
//


package hirs.utils.xjc;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;
import java.math.BigInteger;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the main.java.hirs.utils.xjc package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SPKIData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SPKIData");
    private final static QName _KeyInfo_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyInfo");
    private final static QName _SignatureValue_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureValue");
    private final static QName _KeyValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyValue");
    private final static QName _Transforms_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "Transforms");
    private final static QName _DigestMethod_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "DigestMethod");
    private final static QName _X509Data_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509Data");
    private final static QName _SignatureProperty_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureProperty");
    private final static QName _KeyName_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyName");
    private final static QName _RSAKeyValue_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "RSAKeyValue");
    private final static QName _SoftwareIdentity_QNAME =
            new QName("http://standards.iso.org/iso/19770/-2/2015/schema.xsd", "SoftwareIdentity");
    private final static QName _Signature_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "Signature");
    private final static QName _MgmtData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "MgmtData");
    private final static QName _SignatureMethod_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureMethod");
    private final static QName _Object_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Object");
    private final static QName _SignatureProperties_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureProperties");
    private final static QName _Transform_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "Transform");
    private final static QName _PGPData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "PGPData");
    private final static QName _Reference_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "Reference");
    private final static QName _RetrievalMethod_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "RetrievalMethod");
    private final static QName _DSAKeyValue_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "DSAKeyValue");
    private final static QName _DigestValue_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "DigestValue");
    private final static QName _CanonicalizationMethod_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "CanonicalizationMethod");
    private final static QName _SignedInfo_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "SignedInfo");
    private final static QName _Manifest_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Manifest");
    private final static QName _TransformTypeXPath_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "XPath");
    private final static QName _X509DataTypeX509IssuerSerial_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "X509IssuerSerial");
    private final static QName _X509DataTypeX509CRL_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "X509CRL");
    private final static QName _X509DataTypeX509SubjectName_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "X509SubjectName");
    private final static QName _X509DataTypeX509SKI_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "X509SKI");
    private final static QName _X509DataTypeX509Certificate_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "X509Certificate");
    private final static QName _SoftwareIdentityLink_QNAME =
            new QName("http://standards.iso.org/iso/19770/-2/2015/schema.xsd", "Link");
    private final static QName _SoftwareIdentityEvidence_QNAME =
            new QName("http://standards.iso.org/iso/19770/-2/2015/schema.xsd", "Evidence");
    private final static QName _SoftwareIdentityPayload_QNAME =
            new QName("http://standards.iso.org/iso/19770/-2/2015/schema.xsd", "Payload");
    private final static QName _PayloadDirectory_QNAME =
            new QName("http://standards.iso.org/iso/19770/-2/2015/schema.xsd", "Directory");
    private final static QName _DirectoryFile_QNAME =
            new QName("http://standards.iso.org/iso/19770/-2/2015/schema.xsd", "File");
    private final static QName _SoftwareIdentityEntity_QNAME =
            new QName("http://standards.iso.org/iso/19770/-2/2015/schema.xsd", "Entity");
    private final static QName _SoftwareIdentityMeta_QNAME =
            new QName("http://standards.iso.org/iso/19770/-2/2015/schema.xsd", "Meta");
    private final static QName _SignatureMethodTypeHMACOutputLength_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "HMACOutputLength");
    private final static QName _SPKIDataTypeSPKISexp_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "SPKISexp");
    private final static QName _PGPDataTypePGPKeyID_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "PGPKeyID");
    private final static QName _PGPDataTypePGPKeyPacket_QNAME =
            new QName("http://www.w3.org/2000/09/xmldsig#", "PGPKeyPacket");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for
     * package: main.java.hirs.utils.xjc
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SoftwareIdentity }
     *
     * @return {@link SoftwareIdentity }
     */
    public SoftwareIdentity createSoftwareIdentity() {
        return new SoftwareIdentity();
    }

    /**
     * Create an instance of {@link SoftwareMeta }
     *
     * @return {@link SoftwareMeta }
     */
    public SoftwareMeta createSoftwareMeta() {
        return new SoftwareMeta();
    }

    /**
     * Create an instance of {@link Entity }
     *
     * @return {@link Entity }
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Meta }
     *
     * @return {@link Meta }
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link FilesystemItem }
     *
     * @return {@link FilesystemItem }
     */
    public FilesystemItem createFilesystemItem() {
        return new FilesystemItem();
    }

    /**
     * Create an instance of {@link Resource }
     *
     * @return {@link Resource }
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Process }
     *
     * @return {@link Process }
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link BaseElement }
     *
     * @return {@link BaseElement }
     */
    public BaseElement createBaseElement() {
        return new BaseElement();
    }

    /**
     * Create an instance of {@link Evidence }
     *
     * @return {@link Evidence }
     */
    public Evidence createEvidence() {
        return new Evidence();
    }

    /**
     * Create an instance of {@link File }
     *
     * @return {@link File}
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link Link }
     *
     * @return {@link Link}
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Directory }
     *
     * @return {@link Directory}
     */
    public Directory createDirectory() {
        return new Directory();
    }

    /**
     * Create an instance of {@link ResourceCollection }.
     *
     * @return {@link ResourceCollection }
     */
    public ResourceCollection createResourceCollection() {
        return new ResourceCollection();
    }

    /**
     * Create an instance of {@link PGPDataType }.
     */
    public PGPDataType createPGPDataType() {
        return new PGPDataType();
    }

    /**
     * Create an instance of {@link KeyValueType }.
     *
     * @return {@link KeyValueType }
     */
    public KeyValueType createKeyValueType() {
        return new KeyValueType();
    }

    /**
     * Create an instance of {@link DSAKeyValueType }.
     *
     * @return {@link DSAKeyValueType }
     */
    public DSAKeyValueType createDSAKeyValueType() {
        return new DSAKeyValueType();
    }

    /**
     * Create an instance of {@link ReferenceType }.
     *
     * @return {@link ReferenceType }
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link RetrievalMethodType }.
     *
     * @return {@link RetrievalMethodType }
     */
    public RetrievalMethodType createRetrievalMethodType() {
        return new RetrievalMethodType();
    }

    /**
     * Create an instance of {@link TransformsType }.
     *
     * @return {@link TransformsType }
     */
    public TransformsType createTransformsType() {
        return new TransformsType();
    }

    /**
     * Create an instance of {@link CanonicalizationMethodType }.
     *
     * @return {@link CanonicalizationMethodType }.
     */
    public CanonicalizationMethodType createCanonicalizationMethodType() {
        return new CanonicalizationMethodType();
    }

    /**
     * Create an instance of {@link DigestMethodType }.
     *
     * @return {@link DigestMethodType }
     */
    public DigestMethodType createDigestMethodType() {
        return new DigestMethodType();
    }

    /**
     * Create an instance of {@link ManifestType }.
     *
     * @return {@link ManifestType }
     */
    public ManifestType createManifestType() {
        return new ManifestType();
    }

    /**
     * Create an instance of {@link SignaturePropertyType }.
     *
     * @return {@link SignaturePropertyType }
     */
    public SignaturePropertyType createSignaturePropertyType() {
        return new SignaturePropertyType();
    }

    /**
     * Create an instance of {@link X509DataType }.
     *
     * @return {@link X509DataType }
     */
    public X509DataType createX509DataType() {
        return new X509DataType();
    }

    /**
     * Create an instance of {@link SignedInfoType }.
     *
     * @return {@link SignedInfoType }
     */
    public SignedInfoType createSignedInfoType() {
        return new SignedInfoType();
    }

    /**
     * Create an instance of {@link RSAKeyValueType }.
     *
     * @return {@link RSAKeyValueType }
     */
    public RSAKeyValueType createRSAKeyValueType() {
        return new RSAKeyValueType();
    }

    /**
     * Create an instance of {@link SPKIDataType }.
     *
     * @return {@link SPKIDataType }
     */
    public SPKIDataType createSPKIDataType() {
        return new SPKIDataType();
    }

    /**
     * Create an instance of {@link SignatureValueType }.
     *
     * @return {@link SignatureValueType }
     */
    public SignatureValueType createSignatureValueType() {
        return new SignatureValueType();
    }

    /**
     * Create an instance of {@link KeyInfoType }.
     *
     * @return {@link KeyInfoType }
     */
    public KeyInfoType createKeyInfoType() {
        return new KeyInfoType();
    }

    /**
     * Create an instance of {@link SignatureType }.
     *
     * @return {@link SignatureType }
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link SignaturePropertiesType }.
     *
     * @return {@link SignaturePropertiesType }
     */
    public SignaturePropertiesType createSignaturePropertiesType() {
        return new SignaturePropertiesType();
    }

    /**
     * Create an instance of {@link SignatureMethodType }.
     *
     * @return {@link SignatureMethodType }
     */
    public SignatureMethodType createSignatureMethodType() {
        return new SignatureMethodType();
    }

    /**
     * Create an instance of {@link ObjectType }.
     *
     * @return {@link ObjectType }
     */
    public ObjectType createObjectType() {
        return new ObjectType();
    }

    /**
     * Create an instance of {@link TransformType }.
     *
     * @return {@link TransformType }
     */
    public TransformType createTransformType() {
        return new TransformType();
    }

    /**
     * Create an instance of {@link X509IssuerSerialType }.
     *
     * @return {@link X509IssuerSerialType }
     */
    public X509IssuerSerialType createX509IssuerSerialType() {
        return new X509IssuerSerialType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SPKIDataType }{@code >}}
     *
     * @param value {@link SPKIDataType } representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SPKIData")
    public JAXBElement<SPKIDataType> createSPKIData(SPKIDataType value) {
        return new JAXBElement<>(_SPKIData_QNAME, SPKIDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyInfoType }{@code >}}
     *
     * @param value {@link KeyInfoType } representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "KeyInfo")
    public JAXBElement<KeyInfoType> createKeyInfo(KeyInfoType value) {
        return new JAXBElement<>(_KeyInfo_QNAME, KeyInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureValueType }{@code >}}
     *
     * @param value {@link SignatureValueType } representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureValue")
    public JAXBElement<SignatureValueType> createSignatureValue(SignatureValueType value) {
        return new JAXBElement<>(_SignatureValue_QNAME, SignatureValueType.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyValueType }{@code >}}
     *
     * @param value {@link KeyValueType } representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "KeyValue")
    public JAXBElement<KeyValueType> createKeyValue(KeyValueType value) {
        return new JAXBElement<>(_KeyValue_QNAME, KeyValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransformsType }{@code >}}
     *
     * @param value {@link TransformsType } representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Transforms")
    public JAXBElement<TransformsType> createTransforms(TransformsType value) {
        return new JAXBElement<>(_Transforms_QNAME, TransformsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DigestMethodType }{@code >}}
     *
     * @param value {@link DigestMethodType } representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "DigestMethod")
    public JAXBElement<DigestMethodType> createDigestMethod(DigestMethodType value) {
        return new JAXBElement<>(_DigestMethod_QNAME, DigestMethodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509DataType }{@code >}}
     *
     * @param value {@link X509DataType } representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509Data")
    public JAXBElement<X509DataType> createX509Data(X509DataType value) {
        return new JAXBElement<>(_X509Data_QNAME, X509DataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignaturePropertyType }{@code >}}
     *
     * @param value {@link SignaturePropertyType } representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureProperty")
    public JAXBElement<SignaturePropertyType> createSignatureProperty(SignaturePropertyType value) {
        return new JAXBElement<>(_SignatureProperty_QNAME, SignaturePropertyType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * <p>
     * * @param value string representation of the value
     *
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "KeyName")
    public JAXBElement<String> createKeyName(String value) {
        return new JAXBElement<>(_KeyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RSAKeyValueType }{@code >}}
     *
     * @param value {@link RSAKeyValueType } representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "RSAKeyValue")
    public JAXBElement<RSAKeyValueType> createRSAKeyValue(RSAKeyValueType value) {
        return new JAXBElement<>(_RSAKeyValue_QNAME, RSAKeyValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoftwareIdentity }{@code >}}
     *
     * @param value {@link SoftwareIdentity } representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", name = "SoftwareIdentity")
    public JAXBElement<SoftwareIdentity> createSoftwareIdentity(SoftwareIdentity value) {
        return new JAXBElement<>(_SoftwareIdentity_QNAME, SoftwareIdentity.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}}
     *
     * @param value {@link SignatureType } representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Signature")
    public JAXBElement<SignatureType> createSignature(SignatureType value) {
        return new JAXBElement<>(_Signature_QNAME, SignatureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     * @param value string representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "MgmtData")
    public JAXBElement<String> createMgmtData(String value) {
        return new JAXBElement<>(_MgmtData_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureMethodType }{@code >}}
     *
     * @param value {@link SignatureMethodType } representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureMethod")
    public JAXBElement<SignatureMethodType> createSignatureMethod(SignatureMethodType value) {
        return new JAXBElement<>(_SignatureMethod_QNAME, SignatureMethodType.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectType }{@code >}}
     *
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Object")
    public JAXBElement<ObjectType> createObject(ObjectType value) {
        return new JAXBElement<>(_Object_QNAME, ObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignaturePropertiesType }{@code >}}
     *
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureProperties")
    public JAXBElement<SignaturePropertiesType> createSignatureProperties(SignaturePropertiesType value) {
        return new JAXBElement<>(_SignatureProperties_QNAME,
                SignaturePropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransformType }{@code >}}
     *
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Transform")
    public JAXBElement<TransformType> createTransform(TransformType value) {
        return new JAXBElement<>(_Transform_QNAME, TransformType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PGPDataType }{@code >}}
     *
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "PGPData")
    public JAXBElement<PGPDataType> createPGPData(PGPDataType value) {
        return new JAXBElement<>(_PGPData_QNAME, PGPDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     *
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Reference")
    public JAXBElement<ReferenceType> createReference(ReferenceType value) {
        return new JAXBElement<>(_Reference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrievalMethodType }{@code >}}
     *
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "RetrievalMethod")
    public JAXBElement<RetrievalMethodType> createRetrievalMethod(RetrievalMethodType value) {
        return new JAXBElement<>(_RetrievalMethod_QNAME, RetrievalMethodType.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DSAKeyValueType }{@code >}}
     *
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "DSAKeyValue")
    public JAXBElement<DSAKeyValueType> createDSAKeyValue(DSAKeyValueType value) {
        return new JAXBElement<>(_DSAKeyValue_QNAME, DSAKeyValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement } using the provided byte array for the digest value.
     *
     * @param value byte array representation of the value.
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "DigestValue")
    public JAXBElement<byte[]> createDigestValue(byte[] value) {
        return new JAXBElement<>(_DigestValue_QNAME, byte[].class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CanonicalizationMethodType }{@code >}.
     *
     * @param value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "CanonicalizationMethod")
    public JAXBElement<CanonicalizationMethodType> createCanonicalizationMethod(
            CanonicalizationMethodType value) {
        return new JAXBElement<>(_CanonicalizationMethod_QNAME,
                CanonicalizationMethodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignedInfoType }{@code >}.
     *
     * @param value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignedInfo")
    public JAXBElement<SignedInfoType> createSignedInfo(SignedInfoType value) {
        return new JAXBElement<>(_SignedInfo_QNAME, SignedInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ManifestType }{@code >}.
     *
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Manifest")
    public JAXBElement<ManifestType> createManifest(ManifestType value) {
        return new JAXBElement<>(_Manifest_QNAME, ManifestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}.
     *
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "XPath", scope = TransformType.class)
    public JAXBElement<String> createTransformTypeXPath(String value) {
        return new JAXBElement<>(_TransformTypeXPath_QNAME, String.class, TransformType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509IssuerSerialType }{@code >}.
     *
     * @param value {@link X509IssuerSerialType } representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509IssuerSerial", scope = X509DataType.class)
    public JAXBElement<X509IssuerSerialType> createX509DataTypeX509IssuerSerial(X509IssuerSerialType value) {
        return new JAXBElement<>(_X509DataTypeX509IssuerSerial_QNAME,
                X509IssuerSerialType.class, X509DataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement } using the provided byte array for X509 CRL.
     *
     * @param value byte array representation of the value.
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509CRL", scope = X509DataType.class)
    public JAXBElement<byte[]> createX509DataTypeX509CRL(byte[] value) {
        return new JAXBElement<>(_X509DataTypeX509CRL_QNAME, byte[].class, X509DataType.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement } using the provided string value for the X509 Subject Name.
     *
     * @param value string representation of the value.
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509SubjectName", scope = X509DataType.class)
    public JAXBElement<String> createX509DataTypeX509SubjectName(String value) {
        return new JAXBElement<>(_X509DataTypeX509SubjectName_QNAME, String.class, X509DataType.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement } using the provided byte array for the X509 SKI.
     *
     * @param value byte array representation of the value.
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509SKI", scope = X509DataType.class)
    public JAXBElement<byte[]> createX509DataTypeX509SKI(byte[] value) {
        return new JAXBElement<>(_X509DataTypeX509SKI_QNAME, byte[].class, X509DataType.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement } using the provided byte array for the X509 Certificate.
     *
     * @param value byte array representation of the value.
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509Certificate", scope = X509DataType.class)
    public JAXBElement<byte[]> createX509DataTypeX509Certificate(byte[] value) {
        return new JAXBElement<>(_X509DataTypeX509Certificate_QNAME, byte[].class, X509DataType.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Link }{@code >}.
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", name = "Link", scope = SoftwareIdentity.class)
    public JAXBElement<Link> createSoftwareIdentityLink(Link value) {
        return new JAXBElement<>(_SoftwareIdentityLink_QNAME, Link.class, SoftwareIdentity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Evidence }{@code >}.
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", name = "Evidence", scope = SoftwareIdentity.class)
    public JAXBElement<Evidence> createSoftwareIdentityEvidence(Evidence value) {
        return new JAXBElement<>(_SoftwareIdentityEvidence_QNAME, Evidence.class,
                SoftwareIdentity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceCollection }{@code >}.
     *
     * @param value {@link ResourceCollection} representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", name = "Payload", scope = SoftwareIdentity.class)
    public JAXBElement<ResourceCollection> createSoftwareIdentityPayload(ResourceCollection value) {
        return new JAXBElement<>(_SoftwareIdentityPayload_QNAME, ResourceCollection.class,
                SoftwareIdentity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FilesystemItem }{@code >}}
     *
     * @param value {@link FilesystemItem } representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", name = "Directory", scope = ResourceCollection.class)
    public JAXBElement<FilesystemItem> createPayloadDirectory(FilesystemItem value) {
        return new JAXBElement<>(_PayloadDirectory_QNAME, FilesystemItem.class,
                ResourceCollection.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FilesystemItem }{@code >}}
     *
     * @param value {@link FilesystemItem} representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", name = "File", scope = ResourceCollection.class)
    public JAXBElement<FilesystemItem> createDirectoryFile(FilesystemItem value) {
        return new JAXBElement<>(_DirectoryFile_QNAME, FilesystemItem.class,
                ResourceCollection.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Entity }{@code >}}
     *
     * @param value {@link Entity} representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", name = "Entity", scope = SoftwareIdentity.class)
    public JAXBElement<Entity> createSoftwareIdentityEntity(Entity value) {
        return new JAXBElement<>(_SoftwareIdentityEntity_QNAME, Entity.class, SoftwareIdentity.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoftwareMeta }{@code >}.
     *
     * @param value SoftwareMeta object representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", name = "Meta", scope = SoftwareIdentity.class)
    public JAXBElement<SoftwareMeta> createSoftwareIdentityMeta(SoftwareMeta value) {
        return new JAXBElement<>(_SoftwareIdentityMeta_QNAME, SoftwareMeta.class,
                SoftwareIdentity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}.
     *
     * @param value big integer representation of the value
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "HMACOutputLength", scope = SignatureMethodType.class)
    public JAXBElement<BigInteger> createSignatureMethodTypeHMACOutputLength(BigInteger value) {
        return new JAXBElement<>(_SignatureMethodTypeHMACOutputLength_QNAME, BigInteger.class,
                SignatureMethodType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement } using the provided byte array for the SPKISexp.
     *
     * @param value byte array representation of the value.
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SPKISexp", scope = SPKIDataType.class)
    public JAXBElement<byte[]> createSPKIDataTypeSPKISexp(byte[] value) {
        return new JAXBElement<>(_SPKIDataTypeSPKISexp_QNAME, byte[].class, SPKIDataType.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement } using the provided byte array for the PGPKeyID.
     *
     * @param value byte array representation of the value.
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "PGPKeyID", scope = PGPDataType.class)
    public JAXBElement<byte[]> createPGPDataTypePGPKeyID(byte[] value) {
        return new JAXBElement<>(_PGPDataTypePGPKeyID_QNAME, byte[].class, PGPDataType.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement } using the provided byte array for the PGPKeyPacket.
     *
     * @param value byte array representation of the value.
     * @return {@link JAXBElement }
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "PGPKeyPacket", scope = PGPDataType.class)
    public JAXBElement<byte[]> createPGPDataTypePGPKeyPacket(byte[] value) {
        return new JAXBElement<>(_PGPDataTypePGPKeyPacket_QNAME, byte[].class, PGPDataType.class,
                value);
    }
}
