//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.16 at 06:40:19 PM UTC 
//


package hirs.utils.xjc;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import lombok.Getter;
import lombok.Setter;


/**
 * <p>Java class for SoftwareMeta complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SoftwareMeta">
 *   &lt;complexContent>
 *     &lt;extension base="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}Meta">
 *       &lt;attribute name="activationStatus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="channelType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="colloquialVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="edition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entitlementDataRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="entitlementKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="generator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="persistentId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="product" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="productFamily" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="revision" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="summary" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="unspscCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="unspscVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Getter
@Setter
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoftwareMeta", namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd")
public class SoftwareMeta
        extends Meta {
    @XmlAttribute(name = "activationStatus")
    protected String activationStatus;

    @XmlAttribute(name = "channelType")
    protected String channelType;

    @XmlAttribute(name = "colloquialVersion")
    protected String colloquialVersion;

    @XmlAttribute(name = "description")
    protected String description;

    @XmlAttribute(name = "edition")
    protected String edition;

    @XmlAttribute(name = "entitlementDataRequired")
    protected Boolean entitlementDataRequired;

    @XmlAttribute(name = "entitlementKey")
    protected String entitlementKey;

    @XmlAttribute(name = "generator")
    protected String generator;

    @XmlAttribute(name = "persistentId")
    protected String persistentId;

    @XmlAttribute(name = "product")
    protected String product;

    @XmlAttribute(name = "productFamily")
    protected String productFamily;

    @XmlAttribute(name = "revision")
    protected String revision;

    @XmlAttribute(name = "summary")
    protected String summary;

    @XmlAttribute(name = "unspscCode")
    protected String unspscCode;

    @XmlAttribute(name = "unspscVersion")
    protected String unspscVersion;
}
