#!/usr/bin/env bash

# certificates and key stores generated by this script
CERTIFICATES="/etc/hirs/certificates"

#################
# Key Generation
#################

# leave certificate directory intact on uninstall

#################
# ActiveMQ
#################

# no need to deconfigure, as it will be completely removed during uninstall

#################
# Tomcat
#################

if [[ $1 = "server" ]]; then

    TOMCAT_VERSION='7'
    TOMCAT_MAJOR_VERSION='7'
    CATALINA_HOME=/usr/share/tomcat
    TOMCAT_SERVICE=tomcat
    TOMCAT_CONF=${CATALINA_HOME}/conf/tomcat.conf
    MYSQL_CERT_CONFIG=/etc/mysql/my.cnf

    if [[ -n `grep -o keystorePass $CATALINA_HOME/conf/server.xml` ]]; then
        SERVER_CONF=${CATALINA_HOME}/conf/server.xml
        TOMCAT_USERS=${CATALINA_HOME}/conf/tomcat-users.xml

        echo "Restoring $TOMCAT_CONF"
        sed -i "/^#begin-hirs-conf/,/^#end-hirs-conf/d" "$TOMCAT_CONF"

        echo "Restoring $SERVER_CONF"
        sed -i "s^<Connector port=\"8443\".*/></Service>^</Service>^" "$SERVER_CONF"

        echo "Restoring $TOMCAT_USERS"
        sed -i "s/<user username=\"tomcat\" password=\"tomcat\" roles=\"admin,admin-gui,manager,manager-gui.*<\/tomcat-users>/<\/tomcat-users>/" "$TOMCAT_USERS"
    
    fi
fi

#################
# Appraiser
#################

# no need to deconfigure, as it will be completely removed during uninstall

#################
# MySQL/MariaDB
#################

if [[ $1 = "server" ]]; then
    MYSQL_CERT_DIR=${CERTIFICATES}/mysql/
    if [[ -d $MYSQL_CERT_DIR ]]; then

        if [ -f "/etc/init.d/mariadb" ]; then
            /etc/init.d/mariadb stop  
        elif [ -f "/etc/init.d/mysql" ]; then
            /etc/init.d/mysql stop
        else
            systemctl stop mariadb
        fi

        echo "Restoring Database Config"
        rm -rf $MYSQL_CERT_DIR
        sed -i "/^#begin-hirs-conf/,/^#end-hirs-conf/d" "$MYSQL_CERT_CONFIG"
        
        if [ -f "/etc/init.d/mariadb" ]; then
            /etc/init.d/mariadb start  
        elif [ -f "/etc/init.d/mysql" ]; then
            /etc/init.d/mysql start
        else
            systemctl start mariadb
        fi
        
    fi
fi