package hirs.attestationca.persist.provision.helper;

import hirs.attestationca.persist.enums.TpmEccCurve;
import hirs.attestationca.persist.enums.PublicKeyAlgorithm;
import hirs.attestationca.persist.exceptions.UnexpectedServerException;
import hirs.utils.HexUtils;
import lombok.extern.log4j.Log4j2;

import java.io.DataInputStream;
import java.io.ByteArrayInputStream;
import java.math.BigInteger;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.NoSuchAlgorithmException;
import java.security.interfaces.ECPublicKey;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.ECGenParameterSpec;
import java.security.spec.ECParameterSpec;
import java.security.spec.ECPoint;
import java.security.spec.ECPublicKeySpec;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.InvalidParameterSpecException;
import java.security.spec.RSAPublicKeySpec;
import static hirs.attestationca.persist.provision.helper.ProvisionUtils.DEFAULT_RSA_MODULUS_LENGTH_IN_BYTES;

/**
 *  Helper class for parsing TPM 2.0 public area structures, and constructing public keys from this data.
 *  @see <a href="https://trustedcomputinggroup.org/resource/tpm-library-specification/">
 *  Trusted Platform Module Library Part 2: Structures (TPM 2.0)</a>
 */
@Log4j2
public final class TpmPublicHelper {
    /** Hexadecimal radix used for parsing the RSA public exponent. */
    public static final int RADIX = 16;

    /**
     * Defines the well known exponent.
     * <a href="https://en.wikipedia.org/wiki/65537_(number)#Applications">More information</a>
     */
    private static final BigInteger EXPONENT = new BigInteger("010001", RADIX);

    /** Prevent instantiation. */
    private TpmPublicHelper() { }

    /**
     * Parses the RSA public key from public data segment generated by TPM 2.0.
     * @param publicDataSegment the public area segment to parse
     * @return the RSA public key of the supplied public data
     */
    public static RSAPublicKey parseRSAKeyFromPublicDataSegment(final byte[] publicDataSegment) {
        final int publicDataSegmentLen = publicDataSegment.length;

        if (publicDataSegmentLen < DEFAULT_RSA_MODULUS_LENGTH_IN_BYTES) {
            final String errorMsg = "Could not parse RSA Public Key due to public data segment not being long enough.";
            log.error(errorMsg);
            throw new IllegalArgumentException(errorMsg);
        }

        // public data ends with 256 byte modulus
        byte[] modulus = HexUtils.subarray(publicDataSegment,
                publicDataSegmentLen - DEFAULT_RSA_MODULUS_LENGTH_IN_BYTES, publicDataSegmentLen - 1);
        return assembleRSAPublicKey(modulus);
    }

    /**
     * Constructs an RSA public key where the modulus is Hex encoded.
     * @param modulus in byte array form
     * @return RSA public key using specific modulus and the well known exponent
     */
    public static RSAPublicKey assembleRSAPublicKey(final byte[] modulus) {
        return assembleRSAPublicKey(new BigInteger(1, modulus));
    }

    /**
     * Assembles an RSA public key using a defined big int modulus and the well known exponent.
     * @param modulus modulus
     * @return RSA public key using the provided integer modulus
     */
    public static RSAPublicKey assembleRSAPublicKey(final BigInteger modulus) {
        // generate an RSA key spec using mod and exp
        RSAPublicKeySpec keySpec = new RSAPublicKeySpec(modulus, EXPONENT);

        try { // create the RSA public key
            KeyFactory keyFactory = KeyFactory.getInstance("RSA");
            return (RSAPublicKey) keyFactory.generatePublic(keySpec);
        } catch (NoSuchAlgorithmException | InvalidKeySpecException e) {
            throw new UnexpectedServerException(
                    "Encountered unexpected error creating RSA public key: " + e.getMessage(), e);
        }
    }

    /**
     * Parses the ECC public key from public data segment generated by TPM 2.0.
     * @param publicDataSegment the public area segment to parse
     * @return the ECC public key of the supplied public data
     */
    public static ECPublicKey parseECCKeyFromPublicDataSegment(final byte[] publicDataSegment) {
        Cursor c = new Cursor(publicDataSegment);

        int type = c.readU16(); // Read type
        if (PublicKeyAlgorithm.fromId(type) != PublicKeyAlgorithm.ECC) {
            throw new UnsupportedOperationException("Expected TPM_ALG_ECC");
        }
        c.readU16(); // Skip nameAlg
        c.readU32(); // Skip objectAttributes

        c.skipTpm2b(); // Skip authPolicy
        c.readSymDefObject(); // Skip symdef object
        c.readEccScheme(); // Skip ECC scheme

        int curveId = c.readU16(); // Extract curve family
        TpmEccCurve eccCurve = TpmEccCurve.fromTpmCurveId(curveId).orElseThrow(() -> new UnsupportedOperationException(
                "Unsupported TPM ECC curve ID: 0x" + Integer.toHexString(curveId)));

        c.readKdfScheme(); // Skip KDF scheme

        ECPoint point = new ECPoint(new BigInteger(1, c.readTpm2b()), new BigInteger(1, c.readTpm2b())); // Extract X/Y
        return assembleECCPublicKey(eccCurve, point);
    }

    /**
     * Assembles the ECC public key using the provided curve ID and point.
     * @param curveId curve ID pertaining to ECC curve
     * @param point X/Y point for given curve ID
     * @return the ECC public key
     */
    public static ECPublicKey assembleECCPublicKey(final TpmEccCurve curveId, final ECPoint point) {
        try {
            KeyFactory keyFactory = KeyFactory.getInstance("EC");
            // Create an ECPublicKeySpec object using given curve ID and point
            AlgorithmParameters params = AlgorithmParameters.getInstance("EC");
            params.init(new ECGenParameterSpec(curveId.getJavaName()));
            ECPublicKeySpec spec = new ECPublicKeySpec(point, params.getParameterSpec(ECParameterSpec.class));

            // Generate the ECC public key from the byte array
            return (ECPublicKey) keyFactory.generatePublic(spec);
        } catch (NoSuchAlgorithmException | InvalidKeySpecException | InvalidParameterSpecException e) {
            throw new UnexpectedServerException(
                    "Encountered unexpected error creating ECC public key: " + e.getMessage(), e);
        }
    }

    /**
     * Private utility class to traverse TPMT_PUBLIC structures via a given byte array. These include
     * unsigned 32-bit and 16-bit integers, and the TPM2B structure, including the ability to skip reading.
     */
    private static final class Cursor {
        private final DataInputStream in;

        Cursor(final byte[] buf) {
            if (buf == null) {
                throw new IllegalArgumentException("Input public data segment is null.");
            }
            this.in = new DataInputStream(new ByteArrayInputStream(buf));
        }

        int readU16() {
            try {
                return in.readUnsignedShort();
            } catch (Exception e) {
                throw new IllegalStateException("Exception encountered when parsing public area segment", e);
            }
        }

        long readU32() {
            try {
                return Integer.toUnsignedLong(in.readInt());
            } catch (Exception e) {
                throw new IllegalStateException("Exception encountered when parsing public area segment", e);
            }
        }

        byte[] readTpm2b() {
            int size = readU16();
            byte[] out = new byte[size];
            try {
                in.readFully(out);
                return out;
            } catch (Exception e) {
                throw new IllegalStateException("Exception encountered when parsing public area segment", e);
            }
        }

        void skipTpm2b() {
            int size = readU16();
            skip(size);
        }

        void skip(final int n) {
            try {
                byte[] skipBytes = in.readNBytes(n);
                if (skipBytes.length != n) {
                    throw new IllegalStateException("Encountered unexpected end of public area segment");
                }
            } catch (Exception e) {
                throw new IllegalStateException("Exception encountered when parsing public area segment", e);
            }
        }

        ParsedSymDefObject readSymDefObject() {
            int algId = readU16();
            PublicKeyAlgorithm alg = PublicKeyAlgorithm.fromId(algId); // Read algorithm
            switch (alg) {
                case NULL -> {
                    return new ParsedSymDefObject(algId, null, null);
                }
                case AES -> {
                    int keyBits = readU16();
                    int mode = readU16();
                    return new ParsedSymDefObject(algId, keyBits, mode);
                }
                default -> throw new UnsupportedOperationException("Unsupported TPMT_SYM_DEF_OBJECT alg: 0x"
                        + Integer.toHexString(algId));
            }
        }

        ParsedEccScheme readEccScheme() {
            int algId = readU16();
            PublicKeyAlgorithm alg = PublicKeyAlgorithm.fromId(algId);
            switch (alg) {
                case NULL -> {
                    return new ParsedEccScheme(algId, null);
                }
                case ECDSA, ECDH -> {
                    int hashAlg = readU16();
                    return new ParsedEccScheme(algId, hashAlg);
                }
                default -> throw new UnsupportedOperationException("Unsupported TPMT_ECC_SCHEME alg: 0x"
                        + Integer.toHexString(algId));
            }
        }

        ParsedKdfScheme readKdfScheme() {
            int algId = readU16();
            PublicKeyAlgorithm alg = PublicKeyAlgorithm.fromId(algId);
            if (alg.equals(PublicKeyAlgorithm.NULL)) { // TPM_ALG_NULL only supported for now
                return new ParsedKdfScheme(algId, null);
            }
            throw new UnsupportedOperationException("Unsupported TPMT_KDF_SCHEME alg: 0x"
                    + Integer.toHexString(algId));
        }
    }

    private record ParsedSymDefObject(int alg, Integer keyBits, Integer mode) { }
    private record ParsedEccScheme(int scheme, Integer hashAlg) { }
    private record ParsedKdfScheme(int scheme, Integer hashAlg) { }
}
