package hirs.attestationca.persist.provision.helper;

import hirs.attestationca.persist.enums.TpmEccCurve;
import hirs.attestationca.persist.enums.PublicKeyAlgorithm;
import hirs.attestationca.persist.exceptions.UnexpectedServerException;
import lombok.extern.log4j.Log4j2;

import java.io.DataInputStream;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.math.BigInteger;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.NoSuchAlgorithmException;
import java.security.interfaces.ECPublicKey;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.ECGenParameterSpec;
import java.security.spec.ECParameterSpec;
import java.security.spec.ECPoint;
import java.security.spec.ECPublicKeySpec;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.InvalidParameterSpecException;
import java.security.spec.RSAPublicKeySpec;

/**
 *  Helper class for parsing TPM 2.0 public area structures, and constructing public keys from this data.
 *  @see <a href="https://trustedcomputinggroup.org/resource/tpm-library-specification/">
 *  Trusted Platform Module Library Part 2: Structures (TPM 2.0)</a>
 */
@Log4j2
public final class TpmPublicHelper {
    /** Hexadecimal radix used for parsing the RSA public exponent. */
    public static final int RADIX = 16;

    /**
     * Defines the well known exponent.
     * <a href="https://en.wikipedia.org/wiki/65537_(number)#Applications">More information</a>
     */
    private static final BigInteger EXPONENT = new BigInteger("010001", RADIX);

    /** Prevent instantiation. */
    private TpmPublicHelper() { }

    /**
     * Parses a TPM public area (TPMT_PUBLIC) from a byte array using supported public key algorithms, and returns
     * the parsed structure.
     * <p>
     * todo handle ECC case once Provisioner has been modified to handle ECC keys
     * @param publicArea public area generated by TPM 2.0
     * @return the parsed {@link ParsedTpmPublic} instance
     * @throws IOException if an unexpected parsing issue occurs
     */
    public static ParsedTpmPublic parseTpmPublicArea(final byte[] publicArea) throws IOException {
        if (publicArea == null) {
            throw new IllegalArgumentException("Input public data segment is null.");
        }
        DataInputStream in = new DataInputStream(new ByteArrayInputStream(publicArea));

        //in.skipNBytes(Short.BYTES); // Skip size
        final int type = in.readShort(); // Read type
        final PublicKeyAlgorithm alg = PublicKeyAlgorithm.fromId(type);

        final int nameAlgInt = in.readShort(); // Read nameAlg
        final PublicKeyAlgorithm nameAlg = PublicKeyAlgorithm.fromId(nameAlgInt);

        in.skipNBytes(Integer.BYTES); // Skip objectAttributes

        skipAuthPolicy(in); // Skip authPolicy

        return switch (alg) {
            case RSA -> parsePublicAreaRsa(publicArea, nameAlg, in);
            case ECC -> parsePublicAreaEcc(publicArea, nameAlg, in); // TODO enable
            default -> throw new UnsupportedOperationException("Unsupported or invalid public key algorithm");
        };
    }

    /**
     * Parses the RSA public area structure from TPM 2.0.
     * @param publicArea the public area byte array to parse
     * @param nameAlg the name algorithm
     * @param in the {@link DataInputStream} to continue parsing from
     * @return the {@link ParsedTpmPublic} structure containing parsed RSA data
     * @throws IOException if an unexpected parsing issue occurs
     */
    public static ParsedTpmPublic parsePublicAreaRsa(final byte[] publicArea, final PublicKeyAlgorithm nameAlg,
                                                         final DataInputStream in) throws IOException {
        skipSymDefObject(in); // Skip symdef
        skipRsaScheme(in); // Skip RSA scheme

        final int keyBits = in.readShort(); // Read key bits
        final long exponent = Integer.toUnsignedLong(in.readInt()); // Read exponent
        final byte[] modulusBytes = readTpm2b(in); // Read modulus

        final BigInteger resolvedExponent = (exponent == 0) ? EXPONENT : BigInteger.valueOf(exponent);
        final BigInteger modulus = new BigInteger(1, modulusBytes);

        final RSAPublicKey publicKey = assembleRSAPublicKey(modulus, resolvedExponent); // Assemble public key

        // Return parsed structure
        ParsedTpmPublic.RsaPublicParameters params = new ParsedTpmPublic.RsaPublicParameters(keyBits,
                resolvedExponent, modulus);
        return new ParsedTpmPublic.RsaParsedTpmPublic(PublicKeyAlgorithm.RSA, nameAlg, publicArea.clone(),
                publicKey, params);
    }

    /**
     * Assembles an RSA public key using a defined modulus and exponent.
     * @param modulus modulus
     * @param exponent exponent
     * @return RSA public key using the provided integer modulus
     */
    public static RSAPublicKey assembleRSAPublicKey(final BigInteger modulus, final BigInteger exponent) {
        // generate an RSA key spec using mod and exp
        RSAPublicKeySpec keySpec = new RSAPublicKeySpec(modulus, exponent);

        try { // create the RSA public key
            KeyFactory keyFactory = KeyFactory.getInstance("RSA");
            return (RSAPublicKey) keyFactory.generatePublic(keySpec);
        } catch (NoSuchAlgorithmException | InvalidKeySpecException e) {
            throw new UnexpectedServerException(
                    "Encountered unexpected error creating RSA public key: " + e.getMessage(), e);
        }
    }

    /**
     * Parses the ECC public area structure from TPM 2.0.
     * @param publicArea the public area byte array to parse
     * @param nameAlg the name algorithm
     * @param in the {@link DataInputStream} to continue parsing from
     * @return the {@link ParsedTpmPublic} structure containing parsed ECC data
     * @throws IOException if an unexpected parsing issue occurs
     */
    public static ParsedTpmPublic parsePublicAreaEcc(final byte[] publicArea, final PublicKeyAlgorithm nameAlg,
                                                        final DataInputStream in) throws IOException {
        skipSymDefObject(in); // Skip symdef object
        skipEccScheme(in); // Skip ECC scheme

        int curveId = in.readShort(); // Extract curve family
        TpmEccCurve eccCurve = TpmEccCurve.fromTpmCurveId(curveId).orElseThrow(() -> new UnsupportedOperationException(
                "Unsupported TPM ECC curve ID: 0x" + Integer.toHexString(curveId)));

        skipKdfScheme(in); // Skip KDF scheme

        ECPoint point = new ECPoint(new BigInteger(1, readTpm2b(in)), new BigInteger(1, readTpm2b(in))); // Extract X/Y
        ECPublicKey publicKey = assembleECCPublicKey(eccCurve, point); // Assemble public key

        // Return parsed structure
        ParsedTpmPublic.EccPublicParameters params = new ParsedTpmPublic.EccPublicParameters(eccCurve, point);
        return new ParsedTpmPublic.EccParsedTpmPublic(PublicKeyAlgorithm.ECC, nameAlg, publicArea.clone(),
                publicKey, params);
    }

    /**
     * Assembles the ECC public key using the provided curve ID and point.
     * @param curveId curve ID pertaining to ECC curve
     * @param point X/Y point for given curve ID
     * @return the ECC public key
     */
    public static ECPublicKey assembleECCPublicKey(final TpmEccCurve curveId, final ECPoint point) {
        try {
            KeyFactory keyFactory = KeyFactory.getInstance("EC");
            // Create an ECPublicKeySpec object using given curve ID and point
            AlgorithmParameters params = AlgorithmParameters.getInstance("EC");
            params.init(new ECGenParameterSpec(curveId.getJavaName()));
            ECPublicKeySpec spec = new ECPublicKeySpec(point, params.getParameterSpec(ECParameterSpec.class));

            // Generate the ECC public key from the byte array
            return (ECPublicKey) keyFactory.generatePublic(spec);
        } catch (NoSuchAlgorithmException | InvalidKeySpecException | InvalidParameterSpecException e) {
            throw new UnexpectedServerException(
                    "Encountered unexpected error creating ECC public key: " + e.getMessage(), e);
        }
    }

    private static void skipSymDefObject(final DataInputStream in) throws IOException {
        int algId = in.readShort();
        PublicKeyAlgorithm alg = PublicKeyAlgorithm.fromId(algId); // Read algorithm
        switch (alg) {
            case NULL -> { }
            case AES -> {
                in.skipNBytes(Short.BYTES); // Skip keyBits
                in.skipNBytes(Short.BYTES); // Skip mode
            }
            default -> throw new UnsupportedOperationException("Unsupported TPMT_SYM_DEF_OBJECT alg: 0x"
                    + Integer.toHexString(algId));
        }
    }

    private static void skipEccScheme(final DataInputStream in) throws IOException {
        int algId = in.readShort();
        PublicKeyAlgorithm alg = PublicKeyAlgorithm.fromId(algId);
        switch (alg) {
            case NULL -> { }
            case ECDSA, ECDH -> in.skipNBytes(Short.BYTES); // Skip hashAlg
            default -> throw new UnsupportedOperationException("Unsupported TPMT_ECC_SCHEME alg: 0x"
                    + Integer.toHexString(algId));
        }
    }

    private static void skipRsaScheme(final DataInputStream in) throws IOException {
        int algId = in.readShort();
        PublicKeyAlgorithm alg = PublicKeyAlgorithm.fromId(algId);
        switch (alg) {
            case RSAES, NULL -> { }
            case RSASSA, RSAPSS, OAEP -> in.skipNBytes(Short.BYTES); // Skip hashAlg
            default -> throw new UnsupportedOperationException("Unsupported TPMT_RSA_SCHEME alg: 0x"
                    + Integer.toHexString(algId));
        }
    }

    private static void skipKdfScheme(final DataInputStream in) throws IOException {
        int algId = in.readShort();
        PublicKeyAlgorithm alg = PublicKeyAlgorithm.fromId(algId);
        if (!alg.equals(PublicKeyAlgorithm.NULL)) { // TPM_ALG_NULL only supported for now
            throw new UnsupportedOperationException("Unsupported TPMT_KDF_SCHEME alg: 0x"
                    + Integer.toHexString(algId));
        }
    }

    private static void skipAuthPolicy(final DataInputStream in) throws IOException {
        int size = in.readShort();
        if (size != 0) { // Empty auth policy if zero
            in.skipNBytes(size);
        }
    }

    private static byte[] readTpm2b(final DataInputStream in) throws IOException {
        int size = in.readShort();
        byte[] result = new byte[size];
        in.readFully(result);
        return result;
    }
}
