//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 08:11:19 AM EDT 
//

package hirs.swid.xjc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Use.
 * </p>
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * </p>
 * 
 * <pre>
 * &lt;simpleType name="Use"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="required"/&gt;
 *     &lt;enumeration value="recommended"/&gt;
 *     &lt;enumeration value="optional"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Use", namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd")
@XmlEnum
public enum Use {

	/**
	 * 
	 * The [Link]'d software is absolutely required for installation
	 * 
	 * 
	 */
	@XmlEnumValue("required")
	REQUIRED("required"),

	/**
	 * 
	 * Not absolutely required, but install unless directed not to
	 * 
	 * 
	 */
	@XmlEnumValue("recommended")
	RECOMMENDED("recommended"),

	/**
	 * 
	 * Not absolutely required, install only when asked
	 * 
	 * 
	 */
	@XmlEnumValue("optional")
	OPTIONAL("optional");
	private final String value;

	Use(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static Use fromValue(String v) {
		for (Use c : Use.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
