//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 08:11:19 AM EDT 
//

package hirs.swid.xjc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for Link complex type.
 * </p>
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * </p>
 * <pre>
 * &lt;complexType name="Link"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}BaseElement"&gt;
 *       &lt;attribute name="artifact" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *       &lt;attribute name="media" type="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}Media" /&gt;
 *       &lt;attribute name="ownership" type="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}Ownership" /&gt;
 *       &lt;attribute name="rel" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&gt;
 *       &lt;attribute name="type" type="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}MediaType" /&gt;
 *       &lt;attribute name="use" type="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}Use" /&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Link", namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd")
public class Link extends BaseElement {

	@XmlAttribute(name = "artifact")
	protected String artifact;
	@XmlAttribute(name = "href", required = true)
	@XmlSchemaType(name = "anyURI")
	protected String href;
	@XmlAttribute(name = "media")
	protected String media;
	@XmlAttribute(name = "ownership")
	protected Ownership ownership;
	@XmlAttribute(name = "rel", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NMTOKEN")
	protected String rel;
	@XmlAttribute(name = "type")
	protected String type;
	@XmlAttribute(name = "use")
	protected Use use;

	/**
	 * Gets the value of the artifact property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getArtifact() {
		return artifact;
	}

	/**
	 * Sets the value of the artifact property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setArtifact(String value) {
		this.artifact = value;
	}

	/**
	 * Gets the value of the href property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHref() {
		return href;
	}

	/**
	 * Sets the value of the href property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHref(String value) {
		this.href = value;
	}

	/**
	 * Gets the value of the media property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMedia() {
		return media;
	}

	/**
	 * Sets the value of the media property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMedia(String value) {
		this.media = value;
	}

	/**
	 * Gets the value of the ownership property.
	 * 
	 * @return possible object is {@link Ownership }
	 * 
	 */
	public Ownership getOwnership() {
		return ownership;
	}

	/**
	 * Sets the value of the ownership property.
	 * 
	 * @param value
	 *            allowed object is {@link Ownership }
	 * 
	 */
	public void setOwnership(Ownership value) {
		this.ownership = value;
	}

	/**
	 * Gets the value of the rel property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRel() {
		return rel;
	}

	/**
	 * Sets the value of the rel property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRel(String value) {
		this.rel = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value) {
		this.type = value;
	}

	/**
	 * Gets the value of the use property.
	 * 
	 * @return possible object is {@link Use }
	 * 
	 */
	public Use getUse() {
		return use;
	}

	/**
	 * Sets the value of the use property.
	 * 
	 * @param value
	 *            allowed object is {@link Use }
	 * 
	 */
	public void setUse(Use value) {
		this.use = value;
	}

}
