//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 08:11:19 AM EDT 
//

package hirs.swid.xjc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Ownership.
 * </p>
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * </p>
 * 
 * <pre>
 * &lt;simpleType name="Ownership"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="abandon"/&gt;
 *     &lt;enumeration value="private"/&gt;
 *     &lt;enumeration value="shared"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Ownership", namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd")
@XmlEnum
public enum Ownership {

	/**
	 * 
	 * Determines the relative strength of ownership of the target piece of
	 * software.
	 * 
	 * 
	 */
	@XmlEnumValue("abandon")
	ABANDON("abandon"),

	/**
	 * 
	 * If this is uninstalled, then the [Link]'d software should be removed too.
	 * 
	 * 
	 */
	@XmlEnumValue("private")
	PRIVATE("private"),

	/**
	 * 
	 * If this is uninstalled, then the [Link]'d software should be removed if
	 * nobody else is sharing it
	 * 
	 * 
	 */
	@XmlEnumValue("shared")
	SHARED("shared");
	private final String value;

	Ownership(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static Ownership fromValue(String v) {
		for (Ownership c : Ownership.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
