//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 08:11:19 AM EDT 
//

package hirs.swid.xjc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SoftwareMeta complex type.
 * </p>
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * </p>
 * <pre>
 * &lt;complexType name="SoftwareMeta"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}Meta"&gt;
 *       &lt;attribute name="activationStatus" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="channelType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="colloquialVersion" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="edition" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="entitlementDataRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="entitlementKey" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="generator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="persistentId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="product" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="productFamily" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="revision" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="summary" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="unspscCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="unspscVersion" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;anyAttribute processContents='lax'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoftwareMeta", namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd")
public class SoftwareMeta extends Meta {

	@XmlAttribute(name = "activationStatus")
	protected String activationStatus;
	@XmlAttribute(name = "channelType")
	protected String channelType;
	@XmlAttribute(name = "colloquialVersion")
	protected String colloquialVersion;
	@XmlAttribute(name = "description")
	protected String description;
	@XmlAttribute(name = "edition")
	protected String edition;
	@XmlAttribute(name = "entitlementDataRequired")
	protected Boolean entitlementDataRequired;
	@XmlAttribute(name = "entitlementKey")
	protected String entitlementKey;
	@XmlAttribute(name = "generator")
	protected String generator;
	@XmlAttribute(name = "persistentId")
	protected String persistentId;
	@XmlAttribute(name = "product")
	protected String product;
	@XmlAttribute(name = "productFamily")
	protected String productFamily;
	@XmlAttribute(name = "revision")
	protected String revision;
	@XmlAttribute(name = "summary")
	protected String summary;
	@XmlAttribute(name = "unspscCode")
	protected String unspscCode;
	@XmlAttribute(name = "unspscVersion")
	protected String unspscVersion;

	/**
	 * Gets the value of the activationStatus property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getActivationStatus() {
		return activationStatus;
	}

	/**
	 * Sets the value of the activationStatus property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setActivationStatus(String value) {
		this.activationStatus = value;
	}

	/**
	 * Gets the value of the channelType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getChannelType() {
		return channelType;
	}

	/**
	 * Sets the value of the channelType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setChannelType(String value) {
		this.channelType = value;
	}

	/**
	 * Gets the value of the colloquialVersion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getColloquialVersion() {
		return colloquialVersion;
	}

	/**
	 * Sets the value of the colloquialVersion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColloquialVersion(String value) {
		this.colloquialVersion = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the edition property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEdition() {
		return edition;
	}

	/**
	 * Sets the value of the edition property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEdition(String value) {
		this.edition = value;
	}

	/**
	 * Gets the value of the entitlementDataRequired property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isEntitlementDataRequired() {
		return entitlementDataRequired;
	}

	/**
	 * Sets the value of the entitlementDataRequired property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setEntitlementDataRequired(Boolean value) {
		this.entitlementDataRequired = value;
	}

	/**
	 * Gets the value of the entitlementKey property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEntitlementKey() {
		return entitlementKey;
	}

	/**
	 * Sets the value of the entitlementKey property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEntitlementKey(String value) {
		this.entitlementKey = value;
	}

	/**
	 * Gets the value of the generator property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGenerator() {
		return generator;
	}

	/**
	 * Sets the value of the generator property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGenerator(String value) {
		this.generator = value;
	}

	/**
	 * Gets the value of the persistentId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPersistentId() {
		return persistentId;
	}

	/**
	 * Sets the value of the persistentId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPersistentId(String value) {
		this.persistentId = value;
	}

	/**
	 * Gets the value of the product property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProduct() {
		return product;
	}

	/**
	 * Sets the value of the product property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProduct(String value) {
		this.product = value;
	}

	/**
	 * Gets the value of the productFamily property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductFamily() {
		return productFamily;
	}

	/**
	 * Sets the value of the productFamily property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProductFamily(String value) {
		this.productFamily = value;
	}

	/**
	 * Gets the value of the revision property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRevision() {
		return revision;
	}

	/**
	 * Sets the value of the revision property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRevision(String value) {
		this.revision = value;
	}

	/**
	 * Gets the value of the summary property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSummary() {
		return summary;
	}

	/**
	 * Sets the value of the summary property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSummary(String value) {
		this.summary = value;
	}

	/**
	 * Gets the value of the unspscCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUnspscCode() {
		return unspscCode;
	}

	/**
	 * Sets the value of the unspscCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUnspscCode(String value) {
		this.unspscCode = value;
	}

	/**
	 * Gets the value of the unspscVersion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUnspscVersion() {
		return unspscVersion;
	}

	/**
	 * Sets the value of the unspscVersion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUnspscVersion(String value) {
		this.unspscVersion = value;
	}

}
