//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.16 at 06:40:19 PM UTC 
//


package hirs.attestationca.portal.utils.xjc;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourceCollection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceCollection">
 *   &lt;complexContent>
 *     &lt;extension base="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}BaseElement">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Directory" type="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}Directory"/>
 *         &lt;element name="File" type="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}File"/>
 *         &lt;element name="Process" type="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}Process"/>
 *         &lt;element name="Resource" type="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}Resource"/>
 *       &lt;/choice>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceCollection", namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", propOrder = {
    "directoryOrFileOrProcess"
})
@XmlSeeAlso({
    Evidence.class
})
public class ResourceCollection
    extends BaseElement
{

    @XmlElements({
        @XmlElement(name = "Directory", type = Directory.class),
        @XmlElement(name = "File", type = File.class),
        @XmlElement(name = "Process", type = Process.class),
        @XmlElement(name = "Resource", type = Resource.class)
    })
    protected List<Meta> directoryOrFileOrProcess;

    /**
     * Gets the value of the directoryOrFileOrProcess property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the directoryOrFileOrProcess property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDirectoryOrFileOrProcess().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link hirs.attestationca.portal.utils.xjc.Directory }
     * {@link hirs.attestationca.portal.utils.xjc.File }
     * {@link hirs.attestationca.portal.utils.xjc.Process }
     * {@link hirs.attestationca.portal.utils.xjc.Resource }
     * 
     * 
     */
    public List<Meta> getDirectoryOrFileOrProcess() {
        if (directoryOrFileOrProcess == null) {
            directoryOrFileOrProcess = new ArrayList<Meta>();
        }
        return this.directoryOrFileOrProcess;
    }

}
