//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.16 at 06:40:19 PM UTC 
//


package hirs.attestationca.portal.utils.xjc;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SoftwareIdentity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SoftwareIdentity">
 *   &lt;complexContent>
 *     &lt;extension base="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}BaseElement">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="Entity" type="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}Entity" maxOccurs="unbounded"/>
 *         &lt;element name="Evidence" type="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}Evidence" minOccurs="0"/>
 *         &lt;element name="Link" type="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}Link" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Meta" type="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}SoftwareMeta" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Payload" type="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}ResourceCollection" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="corpus" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="patch" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="media" type="{http://standards.iso.org/iso/19770/-2/2015/schema.xsd}Media" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="supplemental" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="tagId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tagVersion" type="{http://www.w3.org/2001/XMLSchema}integer" default="0" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" default="0.0" />
 *       &lt;attribute name="versionScheme" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" default="multipartnumeric" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoftwareIdentity", namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", propOrder = {
    "entityOrEvidenceOrLink"
})
public class SoftwareIdentity
    extends BaseElement
{

    @XmlElementRefs({
        @XmlElementRef(name = "Meta", namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Link", namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Entity", namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Payload", namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Evidence", namespace = "http://standards.iso.org/iso/19770/-2/2015/schema.xsd", type = JAXBElement.class, required = false)
    })
    @XmlAnyElement(lax = true)
    protected List<Object> entityOrEvidenceOrLink;
    @XmlAttribute(name = "corpus")
    protected Boolean corpus;
    @XmlAttribute(name = "patch")
    protected Boolean patch;
    @XmlAttribute(name = "media")
    protected String media;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "supplemental")
    protected Boolean supplemental;
    @XmlAttribute(name = "tagId", required = true)
    protected String tagId;
    @XmlAttribute(name = "tagVersion")
    protected BigInteger tagVersion;
    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "versionScheme")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String versionScheme;

    /**
     * Gets the value of the entityOrEvidenceOrLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entityOrEvidenceOrLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntityOrEvidenceOrLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link hirs.attestationca.portal.utils.xjc.SoftwareMeta }{@code >}
     * {@link JAXBElement }{@code <}{@link hirs.attestationca.portal.utils.xjc.Link }{@code >}
     * {@link JAXBElement }{@code <}{@link hirs.attestationca.portal.utils.xjc.Entity }{@code >}
     * {@link Object }
     * {@link JAXBElement }{@code <}{@link hirs.attestationca.portal.utils.xjc.ResourceCollection }{@code >}
     * {@link org.w3c.dom.Element }
     * {@link JAXBElement }{@code <}{@link hirs.attestationca.portal.utils.xjc.Evidence }{@code >}
     *
     *
     */
    public List<Object> getEntityOrEvidenceOrLink() {
        if (entityOrEvidenceOrLink == null) {
            entityOrEvidenceOrLink = new ArrayList<Object>();
        }
        return this.entityOrEvidenceOrLink;
    }

    /**
     * Gets the value of the corpus property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isCorpus() {
        if (corpus == null) {
            return false;
        } else {
            return corpus;
        }
    }

    /**
     * Sets the value of the corpus property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setCorpus(Boolean value) {
        this.corpus = value;
    }

    /**
     * Gets the value of the patch property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isPatch() {
        if (patch == null) {
            return false;
        } else {
            return patch;
        }
    }

    /**
     * Sets the value of the patch property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setPatch(Boolean value) {
        this.patch = value;
    }

    /**
     * Gets the value of the media property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMedia() {
        return media;
    }

    /**
     * Sets the value of the media property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMedia(String value) {
        this.media = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the supplemental property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isSupplemental() {
        if (supplemental == null) {
            return false;
        } else {
            return supplemental;
        }
    }

    /**
     * Sets the value of the supplemental property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setSupplemental(Boolean value) {
        this.supplemental = value;
    }

    /**
     * Gets the value of the tagId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * Sets the value of the tagId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTagId(String value) {
        this.tagId = value;
    }

    /**
     * Gets the value of the tagVersion property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getTagVersion() {
        if (tagVersion == null) {
            return new BigInteger("0");
        } else {
            return tagVersion;
        }
    }

    /**
     * Sets the value of the tagVersion property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setTagVersion(BigInteger value) {
        this.tagVersion = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "0.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the versionScheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionScheme() {
        if (versionScheme == null) {
            return "multipartnumeric";
        } else {
            return versionScheme;
        }
    }

    /**
     * Sets the value of the versionScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionScheme(String value) {
        this.versionScheme = value;
    }

}
