Vagrant.configure("2") do |config|
  config.vm.box = "centos-7.4-tpm2tools-v1.1.0"
  config.vm.box_url = "https://rpm:reason-joined-rock@forge.outer.jhuapl.edu/rpm/vagrant-boxes/centos-7.4-x86_64-tpm2-emulator-tpm2-tools_1_1_0_20180308.box"
end
